sudo: required

language: python

services:
  - docker

python:
  - "2.7"

notifications:
  email: false

before_install:
  - docker pull tfarmer/mdmc_dependencies
  - docker run tfarmer/mdmc_dependencies

install:
  - pip install enum34

script:
  - pytest -vv

branches:
  only:
    - master
