# MDMC install config

# For full functionality MDMC requires one or more molecular dynamics (MD)
# engines to be installed. See 'optional-dependencies' for the currently
# supported engines.

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MDMC"
version = "0.2"
description = "A package for optimising classical molecular dynamics parameters by refining against experimental data."
authors = [{name = "MDMC developers", email = "support@mdmcproject.org"}]
requires-python = ">=3.10"
dynamic = ["dependencies"]
readme = "README.md"
keywords = ["neutron scattering", "molecular dynamics"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Physics",
  "Typing :: Typed"
  ]

[project.urls]
Homepage = "https://mdmcproject.org/"
Repository = "https://github.com/MDMCproject/MDMCv0.2_pilot.git"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.optional-dependencies]

### Note that these optional dependencies do not install the requisite molecular
# dynamics engine.
LAMMPS = ["pylammps"]
DLPOLY = ["dlpoly-py @ git+https://gitlab.com/ccp5/dlpoly-py.git"]
###

test = ["pytest==8.3.2",
        "pytest-cov==5.0.0",
        "pytest-cases==3.8.5",
        "pytest-profiling==1.7.0"]
lint = ["ruff==0.5.7"]
typecheck = ["mypy"]
docs = ["sphinx==8.2.3",
        "nbsphinx==0.9.4",
        "sphinx-rtd-theme==2.0.0",
        "docutils==0.20.1",
        "jupyter==1.0.0",
        "nbmake==1.5.4",
        "nbconvert==7.16.4",
        "lxml[html_clean]"]
all = ["MDMC[LAMMPS,DLPOLY,test,lint,typecheck,docs]"]

[project.scripts]
MDMC = "MDMC.utilities.cli:main"

[tool.setuptools.packages.find]
include = ["MDMC*"]

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
]
# remember to use single quotes for regex in TOML
exclude = [  # don't report on objects that match any of these regex
    '\.__[^.]*__$',
]
override_SS05 = [  # override SS05 to allow docstrings starting with these words
    '^Process ',
    '^Assess ',
    '^Access ',
    '^Class ',
]

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 100
indent-width = 4
target-version = "py310"

# Exclude a variety of commonly ignored directories.
extend-exclude = [
    ".#*",
    "__pycache__",
]


[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
select = [
    "PLE", # Pylint errors
    "E",   # Pycodestyle
    "W",   # Pycodestyle warnings
    "F",   # Pyflakes
    "B",   # Flake8 bugbear
    "SIM", # Flake8 Simplify
    "A",   # Flake8 builtins
    "COM", # Flake8 commas
    "FA",  # Flake8 future
    "ISC", # Flake8 implicit string concat
    "RSE", # Flake8 raise
    "I",   # Isort
#    "RUF", # Ruff specific
#    "FURB",# Refurb
#    "PERF",# Perflint
#    "PL",  # Pylint
#    "NPY", # Numpy specific warnings
#    "PTH", # Flake8 use pathlib
#    "D",   # Pydocstyle
#    "UP",  # Pyupgrade
#    "FBT", # Flake8 boolean trap
#    "C4",  # Flake8 comprehensions
#    "PT",  # Flake8 pytest style
#    "Q",   # Flake8 Quotes
#    "RET", # Flake8 return
#    "ARG", # Flake8 unused args

]
ignore = [
    "B028",  # No stacklevel in Warning
    "B905",  # No strict in zip
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.isort]
profile = "black"
