"""
Module for TimeKeeper class to keep track of per-function execution time.
"""

from time import time
from collections import defaultdict


class TimeKeeper():
    """
    A class designed for storing funtion timing information in class variable.

    The idea is to access the class variables
    throught a class instance, typically in a function decorator
    called :any:`time_function_execution`.

    Attributes
    ----------
    number_of_calls : collections.defaultdict[int]
        Number of calls to function.
    execution_time : collections.defaultdict[float]
        Total execution time of function.
    started : float
        Time `TimeKeeper` initialised.
    """

    number_of_calls: defaultdict[int] = defaultdict(int)
    execution_time: defaultdict[float] = defaultdict(float)
    started = time()

    def function_called(self, fname: str):
        """
        Increment function calls for the specified function by 1.

        Parameters
        ----------
        fname : str
            A descriptive name of the function that
            has been called.
            Typically this name will be generated by the
            time_function_execution decorator.
        """
        self.number_of_calls[fname] += 1

    def time_passed(self, fname: str, exp_time: float):
        """
        Accumulate execution time.

        Add the execution time of the function to the accumulated
        execution time from all the times that function has been called.

        Parameters
        ----------
        fname : str
            A descriptive name of the function that
            has been called. Again, if the time_function_execution
            decorator is being used, it will generate the fname.
        exp_time : float
            The wall time that has expired during the
            function execution.
        """
        self.execution_time[fname] += exp_time

    def summarise_results(self) -> list[tuple[str, int, float]]:
        """
        Return recorded function timing data as a list.

        Returns
        -------
        list[tuple[str, int, float]]
             List of entries compsed of the function name,
             number of function calls and accumulated execution time.
        """
        results = []
        for kk, nc in self.number_of_calls.items():
            strk = str(kk)
            if strk in self.execution_time.keys():
                results.append((strk,
                                nc,
                                self.execution_time[kk]))
        return results

    def total_time(self) -> float:
        """
        Return total wall time since we started timing.

        Returns
        -------
        float
            Number of seconds since we started timing
            any of the functions.
        """
        return time() - self.started
