[mypy]
ignore_missing_imports = True
disable_error_code = operator, arg-type, assignment, attr-defined, union-attr, misc, return-value, valid-type, call-overload, var-annotated, override, index, has-type, type-arg, call-arg, func-returns-value, str-format, list-item