name: CI
# contains jobs which run on every pull request
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build docker container
    runs-on: ubuntu-22.04
    # if this is a dependabot PR, skip all this and do the Dependabot workflow instead
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: fetch  # grabs master to compare if Docker build files changed
        run: git fetch origin master

      - name: Check and build container
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BRANCH: ${{ github.head_ref }}
        run: source .github/scripts/build_container.sh

  tests:
    name: Docker tests
    needs: build # so it can use new docker image if docker image has changed
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        testset: ["not lammps and not dlpoly"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Pull Docker Image
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          docker pull -q mdmc/mdmc:ci-$BRANCH || docker pull -q mdmc/mdmc:latest
          echo "IMG_NAME=$(echo $(docker images --filter=reference='mdmc/mdmc:*' --format "{{.Repository}}:{{.Tag}}"))" >> $GITHUB_ENV
      - name: Run tests
        env:
          TESTSET: ${{ matrix.testset }}
        run: |
          docker run -t --mount type=bind,source="$(pwd)",target="$(pwd)" ${{ env.IMG_NAME }} python3 -m pytest -m "$TESTSET" -s $(pwd)/tests/;[ $? -eq 0 ]
          exit 0

      - name: Copy coverage
        run: docker cp $(docker ps -lq):/home/coverage.xml coverage.xml || exit 0
        continue-on-error: true

      - name: Upload code coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  linting:
    name: Ruff
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: apt get
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin python3-tk
        # we use cat and grep here to get the version-pinned pylint version from .dev_requirements.txt; thus we can version control pylint
      - name: pip3 install
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install .[lint,DLPOLY,LAMMPS]
      - name: ruff
        run: |
          ruff check MDMC
          exit $?


  notebooks:
    name: Notebooks
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Pull Docker Image
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          docker pull -q mdmc/mdmc:ci-$BRANCH || docker pull -q mdmc/mdmc:latest
          echo "IMG_NAME=$(echo $(docker images --filter=reference='mdmc/mdmc:*' --format "{{.Repository}}:{{.Tag}}"))" >> $GITHUB_ENV
      - name: Create Docker Container
        run: |
          echo "CONTAINER_HASH=$(echo $(docker run -d -it --mount type=bind,source="$(pwd)",target="/home/mdmc_home" -w "/home/mdmc_home" ${{ env.IMG_NAME }}))" >> $GITHUB_ENV
      - name: Install Requirements
        run: docker exec ${{ env.CONTAINER_HASH }} /bin/bash -c "apt-get install pandoc -y && pip install .[docs]"
      - name: Convert Notebooks
        run: docker exec ${{ env.CONTAINER_HASH }} /bin/bash -c "jupyter nbconvert --config doc/notebook-test-config.py"
      - name: Test Notebooks
        run: docker exec ${{ env.CONTAINER_HASH }} /bin/bash -c "pytest --nbmake --nbmake-timeout=2000 -k ".nbconvert.ipynb""

  type-checking:
    name: Mypy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: apt get
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev openmpi-bin
    - name: pip3 install
      run: |
        sudo pip3 install --upgrade pip
        sudo pip3 install .[typecheck]
    - name: mypy
      run: |
        cd MDMC
        mypy . --show-error-codes --pretty

  benchmark:
    name: Benchmark this commit against last
    runs-on: ubuntu-22.04
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup some dependencies
        shell: bash -l {0}
        run:
          pip install asv

      - name: Run benchmarks
        shell: bash -l {0}
        run: |
          set -x

          # ID this runner
          asv machine --yes

          # Run benchmarks for last commit against previous one
          asv continuous --split --show-stderr 'HEAD^' 'HEAD'