name: Dependabot CI
# separate workflow for Dependabot that avoids using secrets
# as Dependabot does not have access to regular secrets
on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Dependabot workflow
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build Docker container
      env:
        BRANCH: ${{ github.head_ref }}
      run: docker build -t mdmc/mdmc:ci-$BRANCH -f "$(pwd)"/build/Docker/Dockerfile.mdmc . || exit 1
    - name: Run tests
      env:
        BRANCH: ${{ github.head_ref }}
      run: docker run -t --mount type=bind,source="$(pwd)",target="$(pwd)" mdmc/mdmc:ci-$BRANCH python3 -m pytest -s "$(pwd)"/tests/; [ $? -eq 0 ]
    - name: Try to build documentation
      env:
        BRANCH: ${{ github.head_ref }}
      run: docker run -t --mount type=bind,source="$(pwd)",target="$(pwd)" mdmc/mdmc:ci-$BRANCH /bin/bash -c  "cd $(pwd) && apt-get update && apt-get install pandoc -y && pip3 install . && make -d -C $(pwd)/doc html"
    - name: Push image
      env:
        BRANCH: ${{ github.head_ref }}
        DOCKER_PASSWORD: ${{ secrets.DEPENDABOT_DOCKER }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "mdmc" --password-stdin
        docker push mdmc/mdmc:ci-$BRANCH
