name: deploy
# deployment jobs for when master is updated

on:
  pull_request:
    branches: [master]
    types: [closed]

# note that the workflow will be triggered whenever a PR is closed, but the "if:" line of the job means the job will only run if it is closed due to merge
jobs:
  changes:
    name: Check for Docker changes
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      docker_change: ${{ steps.filter.outputs.docker }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docker:
            - 'build/Docker/Dockerfile.engines'
            - 'build/Docker/Dockerfile.mdmc'
            - 'requirements.txt'
            - 'pyproject.toml'

  update-latest-image:
    name: Update Docker image
    needs: changes
    if: ${{ github.event.pull_request.merged == true && needs.changes.outputs.docker_change == 'true' }}
    # just need an env that include docker, here picked:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "mdmc" --password-stdin

    - name: Update frontend image for Python modules
      env:
        BRANCH: ${{ github.head_ref }}
      run: |
        BRANCH="${BRANCH//\//-}"
        # If no image (mdmc/mdmc:ci-$BRANCH) was created for this PR, just exit as a success
        docker pull mdmc/mdmc:ci-$BRANCH || exit 0
        docker tag mdmc/mdmc:ci-$BRANCH mdmc/mdmc:latest
        docker push mdmc/mdmc:latest

    - name: Update backend image for MD engines
      env:
        BRANCH: ${{ github.head_ref }}
      run: |
        BRANCH="${BRANCH//\//-}"
        # If no image (mdmc/engines:ci-$BRANCH) was created for this PR, just exit as a success
        docker pull mdmc/engines:ci-$BRANCH || exit 0
        docker tag mdmc/engines:ci-$BRANCH mdmc/engines:latest
        docker push mdmc/engines:latest

  update-master-profiling:
    name: Update master profiling data
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Download master profiling for comparison
      # regular download artifact can only get artifacts from latest run
      uses: dawidd6/action-download-artifact@v7
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: ci-cron.yml
        name: cron-total-profiling

    - name: Rename to master profiling
      run: mv cron-total-profiling.csv master-profiling.csv

    - name: Upload as master profiling
      uses: actions/upload-artifact@v4
      with:
        name: master-profiling
        path: master-profiling.csv

  doc-deploy:
    name: Documentation-deploy
    needs: update-latest-image
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build documentation
      run: docker run -t --mount type=bind,source="$(pwd)",target="$(pwd)" mdmc/mdmc:latest /bin/bash -c "cd $(pwd) && apt-get update && apt-get install pandoc -y && pip3 install .[docs] && sphinx-apidoc $(pwd)/MDMC -o $(pwd)/doc/reference/api/ && make -d -C $(pwd)/doc html"
    - name: Deploy
      env:
        token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
      run: |
        git clone https://github.com/MDMCproject/MDMCproject.github.io
        cd ./MDMCproject.github.io
        cp -r  ../doc/_build/html/* ../MDMCproject.github.io/
        git config --global user.name "Github Actions"
        git add *
        git commit -a -m "CI deployment"
        git merge -X ours master
        git push https://$token@github.com/MDMCproject/MDMCproject.github.io

  prune-images:
    name: Prune Old Docker Hub Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Prune images
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: source .github/scripts/prune_docker_hub.sh
