name: Dependabot CI
# separate workflow for Dependabot that avoids using secrets
# as Dependabot does not have access to regular secrets
on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Dependabot workflow
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.11.2'
        architecture: x64
    - name: Checkout repo
      uses: actions/checkout@v7
    - name: Install MDMC
      run: pip install .[test,docs]
    - name: Run tests
      working-directory: tests
      run: pytest
    - name: Try to build documentation
      run: apt-get install pandoc -y && make -d -C doc html
