name: deploy
# deployment jobs for when master is updated

on:
  pull_request:
    branches: [master]
    types: [closed]

# note that the workflow will be triggered whenever a PR is closed, but the "if:" line of the job means the job will only run if it is closed due to merge
jobs:
  update-master-profiling:
    name: Update master profiling data
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Download master profiling for comparison
      # regular download artifact can only get artifacts from latest run
      uses: dawidd6/action-download-artifact@v7
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: ci-cron.yml
        name: cron-total-profiling

    - name: Rename to master profiling
      run: mv cron-total-profiling.csv master-profiling.csv

    - name: Upload as master profiling
      uses: actions/upload-artifact@v4
      with:
        name: master-profiling
        path: master-profiling.csv

  doc-deploy:
    name: Documentation-deploy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build documentation
      run: |
        sudo apt-get update
        sudo apt-get install pandoc -y
        pip3 install .[docs]
        sphinx-apidoc MDMC -o doc/reference/api/
        make -d -C doc html
    - name: Deploy
      env:
        token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
      run: |
        git clone https://github.com/MDMCproject/MDMCproject.github.io
        cd ./MDMCproject.github.io
        cp -r  ../doc/_build/html/* ../MDMCproject.github.io/
        git config --global user.name "Github Actions"
        git add *
        git commit -a -m "CI deployment"
        git merge -X ours master
        git push https://$token@github.com/MDMCproject/MDMCproject.github.io
