name: review
# contains jobs which run when a PR is reviewed or approved
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:

  full_tests:
    name: Tests including MD
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Install MDMC
        run: |
          sudo apt-get install libgfortran5 -y
          pip install .[all] && pip install packmol
      - name: Run tests
        working-directory: test
        run: pytest
      - name: Copy profiling info, download profile script reqs. and profile
        run: |
          pip3 install pandas
          python3 .github/scripts/process_prof_data.py prof/ || exit 1

      - name: Upload code coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  notebooks:
    name: Notebook test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Install Requirements
        run: sudo apt-get install pandoc -y
      - name: Install MDMC
        run: pip install .[test,docs]
      - name: Convert Notebooks
        run: jupyter nbconvert --config doc/notebook-test-config.py
      - name: Test Notebooks
        run: pytest --nbmake --nbmake-timeout=2000 -k '.nbconvert.ipynb'

  documentation:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Install Requirements
        run: apt-get update && apt-get install pandoc -y
      - name: Install MDMC
        run: pip install .[docs]
      - name: Make Documentation
        run: |
          sphinx-apidoc $(pwd)/MDMC -o $(pwd)/doc/reference/api/
          make -d -C $(pwd)/doc html
