name: review
# contains jobs which run when a PR is reviewed or approved
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:

  full_tests:
    name: Tests including MD
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install MDMC
        run: |
          sudo apt-get install libgfortran5
          pip install .[all] && pip install packmol
      - name: Run tests
        working-directory: test
        run: pytest
      - name: Copy profiling info, download profile script reqs. and profile
        run: |
          pip3 install pandas
          python3 .github/scripts/process_prof_data.py prof/ || exit 1

      - name: Upload code coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

  basic_tests:
    name: Non-container and not inc MD tests
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'
        architecture: x64
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: pip install
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[all]
    - name: Run tests
      #we have to use --ignore instead of -m "not lammps" because pytest reads the whole script before deselecting - thus throwing an error about not having lammps before the mark can be filtered out
      run: python3 -m pytest -s $(pwd)/tests/ --ignore tests/MD/packmol --ignore=tests/system_tests --ignore=tests/test_imports.py --ignore=tests/MD/test_trajectory.py
    - name: Uninstall
      run: pip3 uninstall -y MDMC

  windows:
    name: Python 3.10.11 on Windows (installation check only)
    runs-on: windows-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.11'
        architecture: x64
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install
      run: |
        pip3 install --upgrade pip
        pip3 install wheel
        pip3 install .

    - name: Uninstall
      run: pip3 uninstall -y MDMC

  documentation:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Requirements
        run: apt-get update && apt-get install pandoc -y
      - name: Install MDMC
        run: pip install .[docs]
      - name: Make Documentation
        run: |
          sphinx-apidoc $(pwd)/MDMC -o $(pwd)/doc/reference/api/
          make -d -C $(pwd)/doc html
